### ISSUE TITLE
Crash because of unset `SUBJECTS_DIR` 

### ISSUE THREAD

**Issue by oesteban** [nipreps/smriprep#252]
My environment has a default setting for SUBJECTS_DIR:

```bash
$ echo $SUBJECTS_DIR
/opt/freesurfer/subjects
```

although it may be some installation error on my side, there's a chance that we are mishandling the environment variable.

Trying to run fMRIPrep on ds003011 (openneuro) crashes with:

```
210712-17:20:52,327 nipype.workflow IMPORTANT:
         
    Running fMRIPREP version 20.2.1+82.g3a00b21c:
      * BIDS dataset path: /home/oesteban/data/ds003011.
      * Participant list: ['02'].
      * Run identifier: 20210712-172043_859ad4a9-6926-4d5d-a6f6-768e87a0633f.
      * Output spaces: MNI152NLin2009cAsym:res-native MNI152NLin6Asym:res-native.
      * Pre-run FreeSurfer's SUBJECTS_DIR: /home/oesteban/tmp/fmriprep-ds003011/out/freesurfer.
Process Process-2:
Traceback (most recent call last):
  File "/home/oesteban/.miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/oesteban/.miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/oesteban/workspace/fmriprep/fmriprep/cli/workflow.py", line 82, in build_workflow
    retval["workflow"] = init_fmriprep_wf()
  File "/home/oesteban/workspace/fmriprep/fmriprep/workflows/base.py", line 64, in init_fmriprep_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/home/oesteban/workspace/fmriprep/fmriprep/workflows/base.py", line 238, in init_single_subject_wf
    anat_preproc_wf = init_anat_preproc_wf(
  File "/home/oesteban/workspace/smriprep/smriprep/workflows/anatomical.py", line 337, in init_anat_preproc_wf
    anat_template_wf = init_anat_template_wf(
  File "/home/oesteban/workspace/smriprep/smriprep/workflows/anatomical.py", line 685, in init_anat_template_wf
    StructuralReference(
  File "/home/oesteban/workspace/nipype/nipype/interfaces/freesurfer/base.py", line 244, in __init__
    super(FSCommandOpenMP, self).__init__(**inputs)
  File "/home/oesteban/workspace/nipype/nipype/interfaces/freesurfer/base.py", line 132, in __init__
    self._subjects_dir = Info.subjectsdir()
  File "/home/oesteban/workspace/nipype/nipype/interfaces/freesurfer/base.py", line 110, in subjectsdir
    return os.environ["SUBJECTS_DIR"]
  File "/home/oesteban/.miniconda/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'SUBJECTS_DIR'
```

Single-session datasets (e.g., ds030) crash later down the line:

```
Process Process-2:
Traceback (most recent call last):
  File "/home/oesteban/.miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/oesteban/.miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/oesteban/workspace/fmriprep/fmriprep/cli/workflow.py", line 82, in build_workflow
    retval["workflow"] = init_fmriprep_wf()
  File "/home/oesteban/workspace/fmriprep/fmriprep/workflows/base.py", line 64, in init_fmriprep_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/home/oesteban/workspace/fmriprep/fmriprep/workflows/base.py", line 238, in init_single_subject_wf
    anat_preproc_wf = init_anat_preproc_wf(
  File "/home/oesteban/workspace/smriprep/smriprep/workflows/anatomical.py", line 517, in init_anat_preproc_wf
    surface_recon_wf = init_surface_recon_wf(
  File "/home/oesteban/workspace/smriprep/smriprep/workflows/surfaces.py", line 227, in init_surface_recon_wf
    RobustRegister(auto_sens=True, est_int_scale=True), name="fsnative2t1w_xfm"
  File "/home/oesteban/workspace/nipype/nipype/interfaces/freesurfer/base.py", line 132, in __init__
    self._subjects_dir = Info.subjectsdir()
  File "/home/oesteban/workspace/nipype/nipype/interfaces/freesurfer/base.py", line 110, in subjectsdir
    return os.environ["SUBJECTS_DIR"]
  File "/home/oesteban/.miniconda/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'SUBJECTS_DIR'
```

**Comment by oesteban** [comment]
Sorry about the noise - SUBJECTS_DIR was not defined as an environment variable, but rather as a bash variable. Apologies.
