### ISSUE TITLE
indexed_gzip.indexed_gzip.CrcError: CRC/size validation failed - the GZIP data might be corrupt

### ISSUE THREAD

**Issue by oesteban** [nipreps/smriprep#265]
Source: https://neurostars.org/t/fmriprep-errors-recon-report-and-mri-coreg/20048

```
Node: fmriprep_wf.single_subject_J1121053_wf.func_preproc_task_motor_run_3_wf.bold_reg_wf.bbreg_wf.mri_coreg
Working directory: /tmp/work/fmriprep_wf/single_subject_J1121053_wf/func_preproc_task_motor_run_3_wf/bold_reg_wf/bbreg_wf/mri_coreg

Node inputs:

args = <undefined>
brute_force_limit = <undefined>
brute_force_samples = <undefined>
compress_report = auto
conform_reference = <undefined>
dof = 6
environ = {'SUBJECTS_DIR': '/opt/freesurfer/subjects'}
ftol = 0.0001
initial_rotation = <undefined>
initial_scale = <undefined>
initial_shear = <undefined>
initial_translation = <undefined>
linmintol = 0.01
max_iters = <undefined>
no_brute_force = <undefined>
no_coord_dithering = <undefined>
no_cras0 = <undefined>
no_intensity_dithering = <undefined>
no_smooth = <undefined>
num_threads = 3
out_lta_file = True
out_params_file = <undefined>
out_reg_file = <undefined>
out_report = report.svg
ref_fwhm = <undefined>
reference_file = <undefined>
reference_mask = <undefined>
saturation_threshold = <undefined>
sep = [4]
source_file = <undefined>
source_mask = <undefined>
source_oob = <undefined>
subject_id = <undefined>
subjects_dir = /opt/freesurfer/subjects

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/freesurfer/base.py", line 149, in run
    return super(FSCommand, self).run(**inputs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 429, in run
    runtime = self._post_run_hook(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/freesurfer.py", line 230, in _post_run_hook
    runtime = super(TruncateLTA, self)._post_run_hook(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/registration.py", line 331, in _post_run_hook
    return super(MRICoregRPT, self)._post_run_hook(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/mixins/reporting.py", line 50, in _post_run_hook
    self._generate_report()
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/report_base.py", line 47, in _generate_report
    contour_nii = load_img(self._contour) if self._contour is not None else None
  File "/usr/local/miniconda/lib/python3.7/site-packages/nilearn/image/image.py", line 1063, in load_img
    return check_niimg(img, wildcards=wildcards, dtype=dtype)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nilearn/_utils/niimg_conversions.py", line 263, in check_niimg
    niimg = load_niimg(niimg, dtype=dtype)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nilearn/_utils/niimg.py", line 121, in load_niimg
    niimg = nibabel.load(niimg)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/loadsave.py", line 52, in load
    img = image_klass.from_filename(filename, **kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/dataobj_images.py", line 489, in from_filename
    keep_file_open=keep_file_open)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/freesurfer/mghformat.py", line 575, in from_file_map
    header = klass.header_class.from_fileobj(mghf)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/freesurfer/mghformat.py", line 170, in from_fileobj
    np.prod(hdr_str_to_np['dims']))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/openers.py", line 168, in seek
    return self.fobj.seek(*args, **kwargs)
  File "indexed_gzip/indexed_gzip.pyx", line 635, in indexed_gzip.indexed_gzip._IndexedGzipFile.seek
indexed_gzip.indexed_gzip.CrcError: CRC/size validation failed - the GZIP data might be corrupt
```

**Comment by mgxd** [comment]
```
contour_nii = load_img(self._contour) if self._contour is not None else None
```

Looks like a potential problem with the brain mask

**Comment by effigies** [comment]
For `MRICoregRPT`, `self._contour` is `mri/ribbon.mgz`. It looks like a corrupted FreeSurfer directory. Probably not much to do but rerun, but worth verifying that the data is corrupted first.

**Comment by effigies** [comment]
I believe this was user error. Please reopen if you disagree. I'll open an issue with `indexed_gzip` to include the filename in its errors, if possible, to aid in debugging.
